---
title: "CodeBook"
author: "Monica"
date: "Sunday, September 21, 2014"
output: html_document
---

The data processed in this assignment comes from this URL
https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip.

The variables selected in these work are those corresponding to mean and standard deviations of those generated by the authors.

A description of how the original authors generated these variables can be accesed in the features_info.txt file located de zip file mention above.

The authors divided the data in two files (train.txt and test.txt) and for this assignment both files were merged. 

Separate files with subjects and activities for each observation in those data sets were provided.

The new data set generated for this assignment contain both data sets with the subject and activities, also a new variable that indicates from which data set each observation comes from.

In order to create this new data set the following steps were followed:

* A subset of the X_test.txt that contain only the columns needed (those corresponding to means and standard deviation of the variables measured)was made.
* Then the file containing the subject data was merge with the subset data.
* The file with the activity data was transformed so instead of numbers for the activities names were assigned. 
	Walk for WALKING
	WalkUp for WALKING_UPSTAIRS
	WalkDown for WALKING_DOWNSTAIRS
	Sit for SITTING
	Stand for STANDING
	Lay for LAYING
* These vector of names was added to the previous data set created.
* A new character variable name type that specified that the data come from the test group, was created and added to the data set.
* The same process was performed with the X_train.txt data set and finally they were merged.
* To create the summary the merged dataset was converted to a tbl format to use with the dplyr package. 
* The data was grouped by activities and by subjects.
* Means of the variables by activities and subjects were calculated and a new table was created. This new table named TidyDataSet.txt was submitted.
* New names were assigned to the variables with the intention of making them easier to use.
* These are the names of the variables:


	New names,		Original  names
			
+	Activities,		new
+	Subject,		new
+	MeanTimeBodyAcceleration_X, 		1 tBodyAcc-mean()-X
+	MeanTimeBodyAcceleration_Y, 		2 tBodyAcc-mean()-Y
+	MeanTimeBodyAcceleration_Z, 		3 tBodyAcc-mean()-Z
+	StdTimeBodyAcceleration_X,		4 tBodyAcc-std()-X
+	StdTimeBodyAcceleration_Y,		5 tBodyAcc-std()-Y
+	StdTimeBodyAcceleration_Z,		6 tBodyAcc-std()-Z
+	MeanTimeGravityAcceleration_X,		41 tGravityAcc-mean()-X
+	MeanTimeGravityAcceleration_Y,		42 tGravityAcc-mean()-Y
+	MeanTimeGravityAcceleration_Z,		43 tGravityAcc-mean()-Z
+	StdTimeGravityAcceleration_X,		44 tGravityAcc-std()-X
+	StdTimeGravityAcceleration_Y,		45 tGravityAcc-std()-Y
+	StdTimeGravityAcceleration_Z,		46 tGravityAcc-std()-Z
+	MeanTimeBodyJerk_X,		81 tBodyAccJerk-mean()-X
+	MeanTimeBodyJerk_Y,		82 tBodyAccJerk-mean()-Y
+	MeanTimeBodyJerk_Z,		83 tBodyAccJerk-mean()-Z
+	StdTimeBodyJerk_X,		84 tBodyAccJerk-std()-X
+	StdTimeBodyJerk_Y,		85 tBodyAccJerk-std()-Y
+	StdTimeBodyJerk_Z,		86 tBodyAccJerk-std()-Z
+	MeanTimeBodyGyro_X,		121 tBodyGyro-mean()-X
+	MeanTimeBodyGyro_Y,		122 tBodyGyro-mean()-Y
+	MeanTimeBodyGyro_Z,		123 tBodyGyro-mean()-Z
+	StdTimeBodyGyro_X,		124 tBodyGyro-std()-X
+	StdTimeBodyGyro_Y,		125 tBodyGyro-std()-Y
+	StdTimeBodyGyro_Z,		126 tBodyGyro-std()-Z
+	MeanTimeBodyGyrojerk_X,		161 tBodyGyroJerk-mean()-X
+	MeanTimeBodyGyrojerk_Y,		162 tBodyGyroJerk-mean()-Y
+	MeanTimeBodyGyrojerk_Z,		163 tBodyGyroJerk-mean()-Z
+	StdTimeBodyGyrojerk_X,		164 tBodyGyroJerk-std()-X
+	StdTimeBodyGyrojerk_Y,		165 tBodyGyroJerk-std()-Y
+	StdTimeBodyGyrojerk_Z,		166 tBodyGyroJerk-std()-Z
+	MeanTimeBodyAccelerationMagnitude,		201 tBodyAccMag-mean()
+	StdTimeBodyAccelerationMagnitude,		202 tBodyAccMag-std()
+	MeanTimeGravityAccelerationMagnitude,		214 tGravityAccMag-mean()
+	StdTimeGravityAccelerationMagnitude,		215 tGravityAccMag-std()
+	MeanTimeBodyAccelerationJerkMagnitude,		227 tBodyAccJerkMag-mean()
+	StdTimeBodyAccelerationJerkMagnitude,		228 tBodyAccJerkMag-std()
+	MeanTimeBodyGyroMagnitude,		240 tBodyGyroMag-mean()
+	StdTimeBodyGyroMagnitude,		241 tBodyGyroMag-std()
+	MeanTimeBodyGyroJerkMagnitude,		253 tBodyGyroJerkMag-mean()
+	StdTimeBodyGyroJerkMagnitude,		254 tBodyGyroJerkMag-std()
+	MeanFrequencyBodyAcceleration_X,		266 fBodyAcc-mean()-X
+	MeanFrequencyBodyAcceleration_Y,		267 fBodyAcc-mean()-Y
+	MeanFrequencyBodyAcceleration_Z,		268 fBodyAcc-mean()-Z
+	StdFrequencyBodyAcceleration_X,		269 fBodyAcc-std()-X
+	StdFrequencyBodyAcceleration_Y,		270 fBodyAcc-std()-Y
+	StdFrequencyBodyAcceleration_Z,		271 fBodyAcc-std()-Z
+	MeanFrequencyBodyAccelerationJerk_X,		345 fBodyAccJerk-mean()-X
+	MeanFrequencyBodyAccelerationJerk_Y,		346 fBodyAccJerk-mean()-Y
+	MeanFrequencyBodyAccelerationJerk_Z,		347 fBodyAccJerk-mean()-Z
+	StdFrequencyBodyAccelerationJerk_X,		348 fBodyAccJerk-std()-X
+	StdFrequencyBodyAccelerationJerk_Y,		349 fBodyAccJerk-std()-Y
+	StdFrequencyBodyAccelerationJerk_Z,		350 fBodyAccJerk-std()-Z
+	MeanFrequencyBodyGyro_X,		424 fBodyGyro-mean()-X
+	MeanFrequencyBodyGyro_Y,		425 fBodyGyro-mean()-Y
+	MeanFrequencyBodyGyro_Z,		426 fBodyGyro-mean()-Z
+	StdFrequencyBodyGyro_X,		427 fBodyGyro-std()-X
+	StdFrequencyBodyGyro_Y,		428 fBodyGyro-std()-Y
+	StdFrequencyBodyGyro_Z,		429 fBodyGyro-std()-Z
+	MeanFrequencyBodyAccelerationMagnitude,		503 fBodyAccMag-mean()
+	StdFrequencyBodyAccelerationMagnitude,		504 fBodyAccMag-std()
+	MeanFrequencyBodyAccelerationJerkMagnitude,		516 fBodyBodyAccJerkMag-mean()
+	StdFrequencyBodyAccelerationJerkMagnitude,		517 fBodyBodyAccJerkMag-std()
+	MeanFrequencyBodyGyroMagnitude,		529 fBodyBodyGyroMag-mean()
+	StdFrequencyBodyGyroMagnitude,		530 fBodyBodyGyroMag-std()
+	MeanTimeBodyAcceleration_Gravity_Angle,		555 angle(tBodyAccMean,gravity)
+	MeanTimeBodyAcceleration_Jerk_MeanGravity_Angle,		556 angle(tBodyAccJerkMean),gravityMean)
+	MeanTimeBodyGyro_MeanGravity_Angle,		557 angle(tBodyGyroMean,gravityMean)
+	MeanTimeBodyGyro_Jerk_MeanGravity_Angle,		558 angle(tBodyGyroJerkMean,gravityMean)
+	MeanGravity_X_Angle,		559 angle(X,gravityMean)
+	MeanGravity_Y_Angle,		560 angle(Y,gravityMean)
+	MeanGravity_Z_Angle,		561 angle(Z,gravityMean)
+	Type		new
